# 本地开发测试使用

version: '3.9'

services:
  f-ai:
    container_name: f-ai
    build: .
    image: 2720851545/f-ai:20221003
    restart: unless-stopped
    network_mode: "host"
    pull_policy: build
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/root/
    environment:
      - F_AI_ENV=test
      - IS_LAZY_LOAD_MODULES=false
    deploy:
     resources:
       limits:
         cpus: '0.3'
#       reservations:
#         cpus: '0.25'
    labels:
      - "traefik.http.routers.f-ai.rule=Host(`f-ai.llyke.lol`)"
      - "traefik.http.services.f-ai.loadbalancer.server.port=8000"
      - "traefik.http.routers.f-ai.tls=true"
      - "traefik.http.routers.f-ai.entrypoints=websecure"
      - "traefik.http.routers.f-ai.tls.certResolver=letsencryptResolver"

      - "traefik.http.routers.f-ai-https.rule=Host(`f-ai.llyke.lol`)"
      - "traefik.http.routers.f-ai-https.entrypoints=web"
      - "traefik.http.routers.f-ai-https.middlewares=http2https"
