version: '3.9'

services:
  f_ocr:
    container_name: f_ocr
    image: 2720851545/f_ocr:20220930
    restart: unless-stopped
    # network_mode: "host"
    # 容器端口暴露, 右侧为容器端口, 左侧为宿主机端口
    ports:
      - "8000:8000"
    # AI模型缓存
    volumes:
      - "./cache:/root/"
    # cpu资源限制, docker-compose要使用最新版本才支持
    deploy:
      resources:
        limits:
          cpus: '0.8'
        reservations:
          cpus: '0.25'
    # traefik配置, 没有使用不用理会
    labels:
      - "traefik.http.routers.f_ocr.rule=Host(`focr.llyke.lol`)"
      - "traefik.http.services.f_ocr.loadbalancer.server.port=8000"
      - "traefik.http.routers.f_ocr.tls=true"
      - "traefik.http.routers.f_ocr.entrypoints=websecure"
      - "traefik.http.routers.f_ocr.tls.certResolver=letsencryptResolver"

      - "traefik.http.routers.f_ocr-https.rule=Host(`focr.llyke.lol`)"
      - "traefik.http.routers.f_ocr-https.entrypoints=web"
      - "traefik.http.routers.f_ocr-https.middlewares=http2https"
